"""add user roles and timestamps

Revision ID: 66fabf8d4c74
Revises: 882b869ccc95
Create Date: 2026-08-24 22:39:47.748878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fabf8d4c74'
down_revision: Union[str, Sequence[str], None] = '882b869ccc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(50), nullable=False, server_default=sa.text("'user'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
