"""timestamp defaults

Revision ID: 8a0a1ee62eb4
Revises: 66fabf8d4c74
Create Date: 2026-08-24 23:35:14.393949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0a1ee62eb4'
down_revision: Union[str, Sequence[str], None] = '66fabf8d4c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
